executor:
  woof: meow
inputs:
  http:
    disabled: False
    plugin: robotica.plugins.inputs.http.HttpInput
    username: admin
    password: q1w2e3r4
  mqtt:
    plugin: robotica.plugins.inputs.mqtt.MqttInput
    disabled: false
    broker_url: mqtt://localhost
    locations: []
outputs:
  audio:
    plugin: robotica.plugins.outputs.audio.AudioOutput
    disabled: False
    sounds:
      prefix: /usr/share/sounds/purple/login.wav
      repeat: /usr/share/sounds/purple/alert.wav
      postfix: /usr/share/sounds/purple/logout.wav
    locations:
      Brian:
        say_cmd:
        - espeak -ven+f5 -k5 {text}
        play_cmd:
        - aplay {file}
        music_play_cmd:
        - mpc clear
        - mpc load {play_list}
        - mpc play
        music_stop_cmd:
        - mpc stop
        music_pause_cmd:
        - mpc pause-if-playing
        music_resume_cmd:
        - mpc play
  lifx:
    plugin: robotica.plugins.outputs.lifx.LifxOutput
    disabled: True
    locations:
      Brian:
      - Brian
      Dining:
      - Kitchen
      Twins:
      - Twins
  mqtt:
    plugin: robotica.plugins.outputs.mqtt.MqttOutput
    disabled: false
    broker_url: mqtt://localhost
    locations: []
